# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Server
gem 'faye-websocket'
gem 'puma'
gem 'rack'

# Utils
gem 'rb-fsevent'
gem 'zeitwerk'

# Database
gem 'sqlite3'
gem 'sequel'
